utils::globalVariables(c(
  "pt_lex", "it_lex", "it_lex_user", "sp_lex", "sp_lex_user", "pt_lex_user",
  "en_lex", "fr_lex",
  "allFeatures",
  "vowels_pt", "consonants_pt",
  "vowels_sp", "consonants_sp",
  "vowels_fr", "consonants_fr",
  "vowels_it", "consonants_it",
  "vowels_en", "consonants_en",
  ".", "pro",
  "proB", "ipa", "syl",
  "cons", "son", "cont",
  "hireg", "ipa", "feature",
  "phoneme", "item", "x",
  "y", "vowel", "score",
  "bigrams_pt", "freq",
  "ngrams", "prop", "prob",
  "nGrams", "n1", "n2", "n3",
  "V1", "V2", "V3", "V4",
  "stress", "input", "output",
  "n_sim", "sd", "cand", "prob",
  "max_h", "exp_h", "Z", "obs",
  "obs_prob", "pred_prob",
  "harmony", "winner", "n"
))
